### ISSUE TITLE
Reliable Broadcast and Identifiable Aborts

### ISSUE THREAD

**Issue by adr1anh** [taurusgroup/multi-party-sig#36]
When a protocol failure occurs due to an adversary sending an incorrect message, the victim will simply abort the execution. 
The error returned by `protocol.Handler` may include information about the misbehaving party if the fault happens during `Round.ProcessMessage()`, since the identity of the sender is known. 
In many cases, this will be due to a failing ZK proof.

Unfortunately, if the attacker only targets a single victim, the other parties will in general not be able to detect whether the victim was in fact attacked, or if they have stopped responding in order to abort the protocol.
Ideally, the victim should be able to inform the other parties of this event, as well as evidence to support their accusal.

To address the above, we will need to modify `protocol.Handler` in the following ways:

## Authenticated Broadcast

A reliable broadcast channel ensures that a message is delivered to all parties, and that all honest parties deliver the same message. 
Without public key infrastructure, this property is impossible to guarantee when `t≥n/3`, whereas the protocols we implement assume only `t<n`.

The requirements for our protocols are a bit different, since we only need to identify misbehaving parties, especially those who send different messages during a broadcast round. 
Our solution goes as follows:

- All Pᵢ send their `message.Message` mᵢ to all parties.
- Pᵢ uses the ECDSA/Schnorr shares as an independent signature key pair, and produces a signature σᵢ ← Signᵢ(mᵢ) for the full message (**including** the header).
- Pᵢ sends (mᵢ,σᵢ) to all Pⱼ and proceeds to the next round.
- Upon reception of (m₁,σ₁),…,(mₙ,σₙ), verify all signatures and compute hᵢ ← H((m₁,σ₁),…,(mₙ,σₙ)).
- When sending the next message mᵢ', Pᵢ includes hᵢ as part of the message.
- Upon reception of mⱼ', Pᵢ checks that hⱼ = hᵢ.
- If the check passes for all parties, then the above steps are repeated for {mⱼ}ⱼ
- If any check fails, Pᵢ sends (m₁,σ₁),…,(mₙ,σₙ) instead of the usual round message.
- All honest parties will have sent the same, and since the messages are signed, the party who sent different messages will be known to all.

## Attribute Faults arising from `Round.ProcessMessage()`

While some errors cannot be attributed to any specific party (mostly those that occur during the `Finalize()` part of a round), errors that arise from a failure to verify a zero-knowledge proof in `ProcessMessage()` can be directly attributed to the sender.
The receiver would still be able to correctly abort, but other parties may have received a correct proof, leading to two possible outcomes:

- The other parties abort due to a timeout from the victim who might be accused of aborting.
- Instead of sending the usual message in `Finalize()`, the victim broadcasts the message to other parties as evidence. 

## Identifiable Abort Rounds 
 
TODO 

## Timeouts

TODO

**Comment by cronokirby** [comment]
This is addressed by the latest merges to main.

**Comment by vherbert** [comment]
README.md does not reflect it is completed. https://github.com/taurusgroup/multi-party-sig#network
